import type { Db } from './client.js';

/**
 * Generates a UUID using PostgreSQL's `gen_random_uuid()`.
 *
 * Every other id in the schema is generated by the database, so batch ids are too
 * — one source of ids rather than two, and the value is guaranteed to be a form
 * the `uuid` columns accept.
 *
 * It costs one round trip, which happens once per user action (a Delegate press, a
 * transfer, a Reconcile commit) rather than per row, so it is not worth
 * optimising away.
 */
export async function newUuid(db: Db): Promise<string> {
  const [row] = await db.$queryRaw<Array<{ id: string }>>`SELECT gen_random_uuid()::text AS id`;
  if (!row) throw new Error('PostgreSQL returned no value for gen_random_uuid()');
  return row.id;
}
